name: full_run
run-name: ${{ github.actor }} is running full python project

on: [push]

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name : build python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name : Install dependencies and run
        run: |  
          python -m pip install --upgrade pip
          pip install numpy pandas scikit-learn  
          python src/main.py
      - name : Upload to artifact
        uses: actions/upload-artifact@v4
        with:
          name: data_artifact
          path: telco_data_head.csv
